import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <h1>Hello World!</h1>
      <p>This is homepage. You can edit me at <code>/pages/index.js</code></p>
      <Link href="./about"><a>Go to About</a></Link>
    </>
  );
}
